server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.0.7:3306/chatdb
    username: chat_app
    password: chatapp

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  # redis:
  # public ip 58.122.234.114
  # host: 192.168.0.7
  # port: 6379
