server:
  address: 0.0.0.0
  port: 9999

spring:
  datasource:
    url: ${CHATAPP_DB_HOST}
    username: ${CHATAPP_DB_USER}
    password: ${CHATAPP_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # host: host.docker.internal

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}

    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

  config:
    import: optional:file:.env

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# logging:
#   level:
#     "[org.thymeleaf]": DEBUG

secretKey: jwt-token-create-secret-key-in-chat-app
