server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://${SERVER_IP}:3306/chatdb
    username: chat_app
    password: chatapp

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: ${SERVER_IP}
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

scrietKey: create-secret-key-in-chat-app
