server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://${SERVER_IP}:3306/chatdb
    username: chat_app
    password: chatapp

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: ${SERVER_IP}
      port: 6379
